<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<DebugType>portable</DebugType>
		<RootNamespace>CanDoItAll.IPFS.Tests</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<!-- https://github.com/tonerdo/coverlet -->
		<!-- Do not collect by default -->
		<CollectCoverage>false</CollectCoverage>
		<CoverletOutputFormat>opencover</CoverletOutputFormat>
		<!--<Exclude>[xunit.*]*</Exclude>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AngleSharp" Version="1.5.2" PrivateAssets="all" />
		<PackageReference Include="bunit.web" Version="1.40.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.10" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.3.2" PrivateAssets="all" />
		<PackageReference Include="MSTest.TestFramework" Version="4.3.2" PrivateAssets="all" />
		<PackageReference Include="coverlet.msbuild" Version="10.0.1" PrivateAssets="all" />
		<PackageReference Include="SharpZipLib" Version="1.4.2" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<ProjectReference Include="..\..\src\CanDoItAll.IPFS.NodeControl.Abstractions\CanDoItAll.IPFS.NodeControl.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\CanDoItAll.IPFS.NodeControl\CanDoItAll.IPFS.NodeControl.csproj" />
		<ProjectReference Include="..\..\src\CanDoItAll.IPFS.Client\CanDoItAll.IPFS.Client.csproj" />
		<ProjectReference Include="..\..\src\CanDoItAll.IPFS.Engine\CanDoItAll.IPFS.Engine.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="starx2.mp4">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="star_trails.mp4">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
