<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CanDoItAll.IPFS.NodeControl.Abstractions</AssemblyName>
    <RootNamespace>CanDoItAll.IPFS.NodeControl</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CanDoItAll.IPFS.Client\CanDoItAll.IPFS.Client.csproj" />
  </ItemGroup>

</Project>
