<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CanDoItAll.IPFS.Client</AssemblyName>
    <RootNamespace>CanDoItAll.IPFS.Client</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS1591;CS0649</NoWarn>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <DebugType>portable</DebugType>

    <AssemblyVersion>0.42</AssemblyVersion>
    <Version>0.42</Version>

    <PackageId>CanDoItAll.IPFS.Client</PackageId>
    <Authors>Richard Schneider</Authors>
    <Title>CanDoItAll IPFS Client</Title>
    <Description>A typed HTTP client for communicating with a CanDoItAll IPFS node.</Description>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>https://github.com/richardschneider/net-ipfs-engine/releases</PackageReleaseNotes>
    <Copyright>© 2018-2019 Richard Schneider</Copyright>
    <PackageTags>ipfs peer-to-peer p2p distributed file-system web http client</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <PackageProjectUrl>https://github.com/richardschneider/net-ipfs-engine</PackageProjectUrl>
    <PackageIconUrl>https://raw.githubusercontent.com/richardschneider/net-ipfs-core/master/doc/images/ipfs-cs-logo-64x64.png</PackageIconUrl>
    <GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' ">true</GeneratePackageOnBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>.pdb;$(AllowedOutputExtensionsInPackageBuildOutputFolder)</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CanDoItAll.IPFS.Engine\CanDoItAll.IPFS.Engine.csproj" />
  </ItemGroup>

</Project>
